---
controller:
  admissionWebhooks:
    annotations:
      argocd.argoproj.io/hook: PostSync
  ingressClass: ingress-nginx-external
  ingressClassResource:
    name: ingress-nginx-external
    enabled: true
  service:
    type: NodePort
    nodePorts:
      http: 31080
      https: 31443
    externalTrafficPolicy: Local
  config:
  resources:
    requests:
      cpu: "250m"
      memory: "200Mi"

