---
controller:
  admissionWebhooks:
    annotations:
      argocd.argoproj.io/hook: PostSync
  ingressClass: ingress-nginx-default
  ingressClassResource:
    name: ingress-nginx-default
    enabled: true
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
    externalTrafficPolicy: Local
  config:
  resources:
    requests:
      cpu: "250m"
      memory: "200Mi"

